<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Over-the-counter payment code settings
    |--------------------------------------------------------------------------
    |
    | Determines whether the app can customize the string values of the
    | over-the-counter payment code generated by the system. This is
    | useful for customizing the payment code string output.
    |
    | Reference: https://developers.xendit.co/api-reference/#create-payment-code
    |
    */
    'enable_custom_payment_code' => env('ENABLE_CUSTOM_PAYMENT_CODE', false),

    'payment_code_prefix' => env('PAYMENT_CODE_PREFIX', ''),

    /*
    |--------------------------------------------------------------------------
    | Collection of business IDs that can use custom payment code
    |--------------------------------------------------------------------------
    |
    | These are collection of business IDs (sub-accounts) which can
    | use custom payment code values rathen than Xendit's default.
    |
    */
    'custom_payment_code_consumer' => array_filter(explode(',', env('CUSTOM_PAYMENT_CODE_CONSUMER', ''))),

    /*
    |--------------------------------------------------------------------------
    | Credit or debit card payment settings (Not yet implemented here)
    |--------------------------------------------------------------------------
    |
    | This determines if the system can accept credit or debit card payments.|
    |
    */
    'card_payments' => env('CARD_PAYMENTS', true),

    /*
    |--------------------------------------------------------------------------
    | Invoice API
    |--------------------------------------------------------------------------
    |
    | This determines if the system can utilize Xendit's invoice API.
    |
    */
    'invoice_api' => env('INVOICE_API', false),

    /*
    |--------------------------------------------------------------------------
    | Payment link
    |--------------------------------------------------------------------------
    |
    | Determines if the system can generate payment links for the customer.
    |
    */
    'payment_link' => env('PAYMENT_LINK', false),

    /*
    |--------------------------------------------------------------------------
    | Commissioning Feature
    |--------------------------------------------------------------------------
    |
    | Determines if the system can issue a commission to agents.
    |
    */
    'payment_code_commission' => env('PAYMENT_CODE_COMMISSION', false),

    /*
    |--------------------------------------------------------------------------
    | SMS Notification
    |--------------------------------------------------------------------------
    |
    | Determines if the system can send SMS notification.
    |
    */
    'can_send_sms_notification' => env('CAN_SEND_SMS_NOTIFICATION', false),

    /*
    |--------------------------------------------------------------------------
    | SMS Notification API Key
    |--------------------------------------------------------------------------
    |
    */
    'semaphore_api_key' => env('SEMAPHORE_API_KEY', null),

    'sms_sender_name' => env('SMS_SENDER_NAME', null),

    /*
    |--------------------------------------------------------------------------
    | Maya Payment Settings
    |--------------------------------------------------------------------------
    |
    */

    'is_maya_payment_enabled' => env('IS_MAYA_PAYMENT_ENABLED', false),
    'success_redirect_url' => env('SUCCESS_REDIRECT_URL', ''),
    'failure_redirect_url' => env('FAILURE_REDIRECT_URL', ''),
    'cancel_redirect_url' => env('CANCEL_REDIRECT_URL', ''),

    /*
    |--------------------------------------------------------------------------
    | QR Code Payment Settings
    |--------------------------------------------------------------------------
    |
    */

    'is_qr_code_payment_enabled' => env('IS_QR_CODE_PAYMENT_ENABLED', false),
];
